# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/bilai/OneDrive/Paris Saclay/ET4/S7/C++/Projet/Magic"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/bilai/OneDrive/Paris Saclay/ET4/S7/C++/Projet/Magic"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/bilai/OneDrive/Paris Saclay/ET4/S7/C++/Projet/Magic/CMakeFiles" "/mnt/c/Users/bilai/OneDrive/Paris Saclay/ET4/S7/C++/Projet/Magic/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/bilai/OneDrive/Paris Saclay/ET4/S7/C++/Projet/Magic/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Magic

# Build rule for target.
Magic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Magic
.PHONY : Magic

# fast build rule for target.
Magic/fast:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/build
.PHONY : Magic/fast

Source/src/Card.o: Source/src/Card.cpp.o

.PHONY : Source/src/Card.o

# target to build an object file
Source/src/Card.cpp.o:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Card.cpp.o
.PHONY : Source/src/Card.cpp.o

Source/src/Card.i: Source/src/Card.cpp.i

.PHONY : Source/src/Card.i

# target to preprocess a source file
Source/src/Card.cpp.i:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Card.cpp.i
.PHONY : Source/src/Card.cpp.i

Source/src/Card.s: Source/src/Card.cpp.s

.PHONY : Source/src/Card.s

# target to generate assembly for a file
Source/src/Card.cpp.s:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Card.cpp.s
.PHONY : Source/src/Card.cpp.s

Source/src/CreatureCard.o: Source/src/CreatureCard.cpp.o

.PHONY : Source/src/CreatureCard.o

# target to build an object file
Source/src/CreatureCard.cpp.o:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/CreatureCard.cpp.o
.PHONY : Source/src/CreatureCard.cpp.o

Source/src/CreatureCard.i: Source/src/CreatureCard.cpp.i

.PHONY : Source/src/CreatureCard.i

# target to preprocess a source file
Source/src/CreatureCard.cpp.i:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/CreatureCard.cpp.i
.PHONY : Source/src/CreatureCard.cpp.i

Source/src/CreatureCard.s: Source/src/CreatureCard.cpp.s

.PHONY : Source/src/CreatureCard.s

# target to generate assembly for a file
Source/src/CreatureCard.cpp.s:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/CreatureCard.cpp.s
.PHONY : Source/src/CreatureCard.cpp.s

Source/src/Deck.o: Source/src/Deck.cpp.o

.PHONY : Source/src/Deck.o

# target to build an object file
Source/src/Deck.cpp.o:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Deck.cpp.o
.PHONY : Source/src/Deck.cpp.o

Source/src/Deck.i: Source/src/Deck.cpp.i

.PHONY : Source/src/Deck.i

# target to preprocess a source file
Source/src/Deck.cpp.i:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Deck.cpp.i
.PHONY : Source/src/Deck.cpp.i

Source/src/Deck.s: Source/src/Deck.cpp.s

.PHONY : Source/src/Deck.s

# target to generate assembly for a file
Source/src/Deck.cpp.s:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Deck.cpp.s
.PHONY : Source/src/Deck.cpp.s

Source/src/EnchantmentCard.o: Source/src/EnchantmentCard.cpp.o

.PHONY : Source/src/EnchantmentCard.o

# target to build an object file
Source/src/EnchantmentCard.cpp.o:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/EnchantmentCard.cpp.o
.PHONY : Source/src/EnchantmentCard.cpp.o

Source/src/EnchantmentCard.i: Source/src/EnchantmentCard.cpp.i

.PHONY : Source/src/EnchantmentCard.i

# target to preprocess a source file
Source/src/EnchantmentCard.cpp.i:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/EnchantmentCard.cpp.i
.PHONY : Source/src/EnchantmentCard.cpp.i

Source/src/EnchantmentCard.s: Source/src/EnchantmentCard.cpp.s

.PHONY : Source/src/EnchantmentCard.s

# target to generate assembly for a file
Source/src/EnchantmentCard.cpp.s:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/EnchantmentCard.cpp.s
.PHONY : Source/src/EnchantmentCard.cpp.s

Source/src/Game.o: Source/src/Game.cpp.o

.PHONY : Source/src/Game.o

# target to build an object file
Source/src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Game.cpp.o
.PHONY : Source/src/Game.cpp.o

Source/src/Game.i: Source/src/Game.cpp.i

.PHONY : Source/src/Game.i

# target to preprocess a source file
Source/src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Game.cpp.i
.PHONY : Source/src/Game.cpp.i

Source/src/Game.s: Source/src/Game.cpp.s

.PHONY : Source/src/Game.s

# target to generate assembly for a file
Source/src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Game.cpp.s
.PHONY : Source/src/Game.cpp.s

Source/src/GameCards.o: Source/src/GameCards.cpp.o

.PHONY : Source/src/GameCards.o

# target to build an object file
Source/src/GameCards.cpp.o:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/GameCards.cpp.o
.PHONY : Source/src/GameCards.cpp.o

Source/src/GameCards.i: Source/src/GameCards.cpp.i

.PHONY : Source/src/GameCards.i

# target to preprocess a source file
Source/src/GameCards.cpp.i:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/GameCards.cpp.i
.PHONY : Source/src/GameCards.cpp.i

Source/src/GameCards.s: Source/src/GameCards.cpp.s

.PHONY : Source/src/GameCards.s

# target to generate assembly for a file
Source/src/GameCards.cpp.s:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/GameCards.cpp.s
.PHONY : Source/src/GameCards.cpp.s

Source/src/LandCard.o: Source/src/LandCard.cpp.o

.PHONY : Source/src/LandCard.o

# target to build an object file
Source/src/LandCard.cpp.o:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/LandCard.cpp.o
.PHONY : Source/src/LandCard.cpp.o

Source/src/LandCard.i: Source/src/LandCard.cpp.i

.PHONY : Source/src/LandCard.i

# target to preprocess a source file
Source/src/LandCard.cpp.i:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/LandCard.cpp.i
.PHONY : Source/src/LandCard.cpp.i

Source/src/LandCard.s: Source/src/LandCard.cpp.s

.PHONY : Source/src/LandCard.s

# target to generate assembly for a file
Source/src/LandCard.cpp.s:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/LandCard.cpp.s
.PHONY : Source/src/LandCard.cpp.s

Source/src/Main.o: Source/src/Main.cpp.o

.PHONY : Source/src/Main.o

# target to build an object file
Source/src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Main.cpp.o
.PHONY : Source/src/Main.cpp.o

Source/src/Main.i: Source/src/Main.cpp.i

.PHONY : Source/src/Main.i

# target to preprocess a source file
Source/src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Main.cpp.i
.PHONY : Source/src/Main.cpp.i

Source/src/Main.s: Source/src/Main.cpp.s

.PHONY : Source/src/Main.s

# target to generate assembly for a file
Source/src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Main.cpp.s
.PHONY : Source/src/Main.cpp.s

Source/src/Player.o: Source/src/Player.cpp.o

.PHONY : Source/src/Player.o

# target to build an object file
Source/src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Player.cpp.o
.PHONY : Source/src/Player.cpp.o

Source/src/Player.i: Source/src/Player.cpp.i

.PHONY : Source/src/Player.i

# target to preprocess a source file
Source/src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Player.cpp.i
.PHONY : Source/src/Player.cpp.i

Source/src/Player.s: Source/src/Player.cpp.s

.PHONY : Source/src/Player.s

# target to generate assembly for a file
Source/src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/Player.cpp.s
.PHONY : Source/src/Player.cpp.s

Source/src/StrColor.o: Source/src/StrColor.cpp.o

.PHONY : Source/src/StrColor.o

# target to build an object file
Source/src/StrColor.cpp.o:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/StrColor.cpp.o
.PHONY : Source/src/StrColor.cpp.o

Source/src/StrColor.i: Source/src/StrColor.cpp.i

.PHONY : Source/src/StrColor.i

# target to preprocess a source file
Source/src/StrColor.cpp.i:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/StrColor.cpp.i
.PHONY : Source/src/StrColor.cpp.i

Source/src/StrColor.s: Source/src/StrColor.cpp.s

.PHONY : Source/src/StrColor.s

# target to generate assembly for a file
Source/src/StrColor.cpp.s:
	$(MAKE) -f CMakeFiles/Magic.dir/build.make CMakeFiles/Magic.dir/Source/src/StrColor.cpp.s
.PHONY : Source/src/StrColor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Magic"
	@echo "... Source/src/Card.o"
	@echo "... Source/src/Card.i"
	@echo "... Source/src/Card.s"
	@echo "... Source/src/CreatureCard.o"
	@echo "... Source/src/CreatureCard.i"
	@echo "... Source/src/CreatureCard.s"
	@echo "... Source/src/Deck.o"
	@echo "... Source/src/Deck.i"
	@echo "... Source/src/Deck.s"
	@echo "... Source/src/EnchantmentCard.o"
	@echo "... Source/src/EnchantmentCard.i"
	@echo "... Source/src/EnchantmentCard.s"
	@echo "... Source/src/Game.o"
	@echo "... Source/src/Game.i"
	@echo "... Source/src/Game.s"
	@echo "... Source/src/GameCards.o"
	@echo "... Source/src/GameCards.i"
	@echo "... Source/src/GameCards.s"
	@echo "... Source/src/LandCard.o"
	@echo "... Source/src/LandCard.i"
	@echo "... Source/src/LandCard.s"
	@echo "... Source/src/Main.o"
	@echo "... Source/src/Main.i"
	@echo "... Source/src/Main.s"
	@echo "... Source/src/Player.o"
	@echo "... Source/src/Player.i"
	@echo "... Source/src/Player.s"
	@echo "... Source/src/StrColor.o"
	@echo "... Source/src/StrColor.i"
	@echo "... Source/src/StrColor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

