.TH "Répertoire de référence de Source/src" 3 "Vendredi 21 Janvier 2022" "Magic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de Source/src
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBCard\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBCreatureCard\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBDeck\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBGame\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBGameCards\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBLandCard\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBMain\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBPlayer\&.cpp\fP"
.br
.ti -1c
.RI "fichier \fBStrColor\&.cpp\fP"
.br
.in -1c
