.TH "Répertoire de référence de Source/header" 3 "Vendredi 21 Janvier 2022" "Magic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de Source/header
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBCard\&.h\fP"
.br
.ti -1c
.RI "fichier \fBCreatureCard\&.h\fP"
.br
.ti -1c
.RI "fichier \fBDeck\&.h\fP"
.br
.ti -1c
.RI "fichier \fBGame\&.h\fP"
.br
.ti -1c
.RI "fichier \fBGameCards\&.h\fP"
.br
.ti -1c
.RI "fichier \fBLandCard\&.h\fP"
.br
.ti -1c
.RI "fichier \fBPlayer\&.h\fP"
.br
.ti -1c
.RI "fichier \fBStrColor\&.h\fP"
.br
.ti -1c
.RI "fichier \fBUtil\&.h\fP"
.br
.in -1c
