.TH "Répertoire de référence de Source" 3 "Vendredi 21 Janvier 2022" "Magic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de Source
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBdata\fP"
.br
.ti -1c
.RI "répertoire \fBheader\fP"
.br
.ti -1c
.RI "répertoire \fBsrc\fP"
.br
.in -1c
