.TH "Source/header/Deck.h" 3 "Vendredi 21 Janvier 2022" "Magic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/header/Deck.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <bits/stdc++\&.h>\fP
.br
\fC#include 'Card\&.h'\fP
.br
\fC#include 'GameCards\&.h'\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeck\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Magic à partir du code source\&.
