.TH "Source/src/Game.cpp" 3 "Vendredi 21 Janvier 2022" "Magic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/src/Game.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <map>\fP
.br
\fC#include '\&.\&./header/Util\&.h'\fP
.br
\fC#include '\&.\&./header/Player\&.h'\fP
.br
\fC#include '\&.\&./header/Deck\&.h'\fP
.br
\fC#include '\&.\&./header/Game\&.h'\fP
.br
\fC#include '\&.\&./header/StrColor\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "std::string \fBcenterString\fP (std::string s, int size)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "std::string centerString (std::string s, int size)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Magic à partir du code source\&.
