.TH "Source/src/Main.cpp" 3 "Vendredi 21 Janvier 2022" "Magic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/src/Main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./header/Card\&.h'\fP
.br
\fC#include '\&.\&./header/CreatureCard\&.h'\fP
.br
\fC#include '\&.\&./header/LandCard\&.h'\fP
.br
\fC#include '\&.\&./header/Game\&.h'\fP
.br
\fC#include '\&.\&./header/Deck\&.h'\fP
.br
\fC#include '\&.\&./header/GameCards\&.h'\fP
.br
\fC#include '\&.\&./dependance/json\&.hpp'\fP
.br

.SS "Définitions de type"

.in +1c
.ti -1c
.RI "using \fBjson\fP = nlohmann::json"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Documentation des définitions de type"
.PP 
.SS "using \fBjson\fP =  nlohmann::json"

.SH "Documentation des fonctions"
.PP 
.SS "int main ()"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Magic à partir du code source\&.
