.TH "Source/header/Player.h" 3 "Vendredi 21 Janvier 2022" "Magic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/header/Player.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Card\&.h'\fP
.br
\fC#include 'Deck\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayer\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Magic à partir du code source\&.
