.TH "Source/src/Player.cpp" 3 "Vendredi 21 Janvier 2022" "Magic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/src/Player.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./header/Player\&.h'\fP
.br
\fC#include '\&.\&./header/StrColor\&.h'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Magic à partir du code source\&.
