.TH "StrColor" 3 "Vendredi 21 Janvier 2022" "Magic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StrColor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StrColor\&.h>\fP
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static std::string \fBprint\fP (std::string str, std::string color)"
.br
.ti -1c
.RI "static std::string \fBred\fP (std::string)"
.br
.ti -1c
.RI "static std::string \fBgreen\fP (std::string)"
.br
.ti -1c
.RI "static std::string \fByellow\fP (std::string)"
.br
.ti -1c
.RI "static std::string \fBblue\fP (std::string)"
.br
.ti -1c
.RI "static std::string \fBmagenta\fP (std::string)"
.br
.ti -1c
.RI "static std::string \fBcyan\fP (std::string)"
.br
.in -1c
.SH "Documentation des fonctions membres"
.PP 
.SS "std::string StrColor::blue (std::string str)\fC [static]\fP"

.SS "std::string StrColor::cyan (std::string str)\fC [static]\fP"

.SS "std::string StrColor::green (std::string str)\fC [static]\fP"

.SS "std::string StrColor::magenta (std::string str)\fC [static]\fP"

.SS "std::string StrColor::print (std::string str, std::string color)\fC [static]\fP"

.SS "std::string StrColor::red (std::string str)\fC [static]\fP"

.SS "std::string StrColor::yellow (std::string str)\fC [static]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Magic à partir du code source\&.
