.TH "Source/header/Util.h" 3 "Vendredi 21 Janvier 2022" "Magic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/header/Util.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <bits/stdc++\&.h>\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "template<typename Base , typename T > bool \fBinstanceof\fP (const T *)"
.br
.ti -1c
.RI "template<typename T > int \fBgetIndex\fP (std::vector< T > v, T K)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "template<typename T > int getIndex (std::vector< T > v, T K)"

.SS "template<typename Base , typename T > bool instanceof (const T *)\fC [inline]\fP"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Magic à partir du code source\&.
